theopensourceway/guidebook

CONTRIBUTING.md
Mentoring.adoc

I'd like to add a [CONTRIBUTING.md](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) file in order to assist new project contributors.
This PR also includes material on mentoring from @quaid.

Add CONTRIBUTING.md file and chapter on mentoring

---

README.md

This is in response to Issue #3 with some barebones material. It's worth confirming that we want these details at this level, or more or less granular.

First useful content for README

---

README.md

As per #6, submitting a batch of README edits.

Update README with minor edits

---

Generate_energy_at_events_talks_etc.adoc

This PR suggests [recent writing on open source events from Donna Benjamin](https://www.redhat.com/en/blog/events-life-force-open-source).

Add section on generating energy at events

---

Conducting_community_elections.adoc

This PR suggests [recent writing on community elections from @dneary](https://www.redhat.com/en/resources/how-to-run-community-elections-brief).

Add section on conducting community elections

---

Contributors_to_a_transparently_run_community_that_provides_the_artifact_to_users_and_extends_every_courtesy_to_the_participants.adoc
From_users_to_contributors.adoc

This PR suggests [recent writing on successfully engaging users from @dneary](https://community.redhat.com/blog/2019/06/engagement-is-a-gift-welcoming-new-community-members/).

Add chapter on engaging users to turn them into contributors

---

marketing/SCaLE_18x_Workshop-_-06_March_2020--content.adoc

I've massaged our description of the proposed workshop in order to make it applicable to all future collateral (handsouts, website copy, etc.).

Update potential workshop description

---

Announcing_Releases.adoc

This PR suggests adding recent material on announcing community releases from @bproffitt.

Add section on announcing community releases

---

community_101.adoc

The PR proposes some general FAQ-style material related to open source software communities. It's intended to supplement the chapter on community fundamentals (see #21).

Add initial communites FAQ material

---

CONTRIBUTING.md
README.md

Responding to @murriel suggestion in #48, this PR suggests revisions to project documents designed to assist new contributors.

Update project README and CONTRIBUTING files

---

onboarding.adoc

This PR suggests new material from @jberkus on the importance of [responding quickly](https://community.redhat.com/blog/author/jberkus/) to contributors, particularly new contributors.
Author granted @semioticrobotic express permission to edit and republish this material.

Add new material on responding quickly to contributors

---

developing_a_metrics_plan.adoc

A basic outline for the metrics section.
@semioticrobotic, let me know what you think...

Outline for for the community metrics chapter

---

self-care_section.adoc

New section with specific chapters to be determined.

Self-care section - FOSDEM 2020 addition

---

avoiding_pitfalls_section.adoc

Stories in this final section have at least two forms:
- Why-to tales in narrative form that are perhaps specific to an experience, industry, etc. that could potentially be swapped in for a different story in a how-to chapter.
- Full transcripts and tagged/categorized tales from interviews of various open source practitioners.

Stories and interviews - FOSDEM/SCaLE addition

---

growing_contributors_section.adoc

The request was both made to us as a project but also as a section for the book--make sure that this chapter about onboarding includes making sure there are easyfix/non-expert ways to participate and contribute.

Onboarding gradients - SCaLE 18x workshop

---

OUTLINE.adoc

These ideas came from discussions during the birds of a feather at FOSDEM and workshop at SCaLE.
I'll roll these into a new section file and content in the existing section files, so the changes appear in all the outline views.
It would be good to find a way to make this easier to keep track of ...

Sections/chapters from FOSDEM 2020, SCaLE 18x

---

CONTRIBUTING.md
README.md

This new content is meant to provide an overview of the writing process so that people coming in have an idea of what is in store for them. It should be detailed enough to be accurate and informative without being overhwhelming and deeply-detailed.

Adding writing workflow overview

---

PROCESS.adoc

Create TOSW Publishing Process Guide

---

creating_diverse_inclusive_communities.adoc

Begin formatting draft chapter on creating diverse and inclusive communities according to basic book conventions

Apply basic formatting

---

creating_diverse_inclusive_communities.adoc

This PR corrects this editor's earlier procedural mistake and re-opens @lmaffeo chapter for editing. I have begun work here, and @lmaffeo indicates that additional material is forthcoming (see #101).

Edit chapter on creating diverse and inclusive communities

---

OUTLINE.adoc
comm_norms.adoc

This is related to issue #134.

Submitting chapter on communication norms in open source projects

---

community-manager-self-care.adoc

This PR contains the main bulk of the the Community Manager Self-Care chapter. The original outline can be found [here](https://github.com/theopensourceway/guidebook/blob/87a08f14e0d63677685c237b5bc30aef55cb23d3/community-manager-self-care.adoc) and a more detailed one [here](https://github.com/theopensourceway/guidebook/pull/69).
I have a few comments to make:
- I assume we all agree to use *American British* spelling. Not a big issue, just need to ensure editors from different regions are aware of that.
- This became an extremely large chapter (from my brief comparison to others). The subject was the community manager themselves and highlighting to them the importance of self-care from their perspective. The spill out from their 'enlightenment' and actions would then cascade to the team …

New Content: Community Manager Self-Care Chapter 

---

onboarding.adoc

This PR suggests some new material from @dneary on mentoring community managers.

Add new material on mentoring community managers

---

community-manager-self-care.adoc

Development edit of chapter, #70

Development edit of self-care chapter.

---

developing_a_metrics_plan.adoc

This chapter is very good, in quite good shape.
I did some work to reduce excess styling and formatting, and got fussy adding additional whitespace within the source side itself to make it easier to edit.
Some edits were to remove idioms or otherwise make it clearer for non-native English readers.
Adding in cross-references (search for "refer to"), for future cross-linking possibilities.

Main copyedit, mostly re-formatting

---

presenting-tosw.adoc

This has been given a development edit. Comments and light edits within.

Development edit of presenting-tosw.adoc

---

community_manager_self_care.adoc

Hi @samus-aran sorry it took me so long, this is comprehensive and thoughtful as I really wanted to help make sure your message, tone, and voice came through most clearly.
These are the edits you and I discussed directly that I could merge ahead of your reading them, and I appreciate the trust. When I build the final preview, if you haven't had the chance to close on these, I will plan to build the preview with this content out of this branch; we can then rebuild (continuously) after you merge this.

Copy, style, and content edit

---

community_roles.adoc

Draft for review. All comments welcome. This draft was developed with input from the team building IEEE SA open https://saopen.ieee.org/

Draft added to  community_roles.adoc

---

community_roles.adoc

Formatting, draft review early edit with suggestions
- Did some formatting to convert from MarkDown to AsciiDoc
- Made one sentence per line for easier reviews of edits
- Commented out and put in some thoughts about the longer documentation sub-section
- Added a comment block at the end to give a full list of the the community roles we might want a sub-section for
- Each of these sub-sections doesn't need to be long, because it can't get in details about tools and processes that will be specific to the project
- Rather each sub-section can describe a bit of "day in the life of this role" and how it interacts in the project, who might be drawn to it, and so forth.
- Didn't get into the specific content in this, figuring to save that for the development edit and copyedit.
- Note that voice …

Pre-draft review, formatting

---

community_roles.adoc

Added a lot of material about writing documents.

Added a lot of material about writing documents

---

attracting_users_section.adoc
introductions_section.adoc

- I accidentally committed the content in this with a previous commit with templates across all files.
- Rather than revert this one, I just made a fix so I can make a PR for an editor to do a full review.
- I like the format here; if others' suggestions cause modifications/evolution, we'll just roll them across the handful of files.

Content draft, format draft idea for section intros

---

guiding_participants_section.adoc

This is the draft section opening for the "Guiding Participants" section. I'm writing this in anticipation of also doing the "how participants help" content, so the promise made here plays out in that chapter.

first draft, pretty happy with this

---

creating_a_culture_of_mentorship.adoc

- Did some content integration; much of this has been copy edited through a few times.
- Adjusted some language and especially the paragraphing to make three authors appear more as one.
- Other formatting fixes, pronoun adjustments.
- Conclusion in place
- I'm calling this ready for Final Review, meaning I think it's done and ready for any other final reviews folks want to do.
Signed-off-by: Karsten Wade <kwade@redhat.com>

Development and copy-edit complete; chapter seems done

---

creating_a_culture_of_mentorship.adoc

I've started making my editorial notes and changes to the chapter on mentorship.

Edit chapter on mentorship

---

creating_a_culture_of_mentorship.adoc

@quaid @palante this chapter looks great 😄  I just spotted a sentence that sounded a bit awkward.

Minor edit

---

CONTRIBUTORS.adoc
the_open_source_way-guidebook-2.0.adoc

I forgot to change my local branch after moving the default over, merging these in to the 'main'

merge in from forgot-to-branch-locally

---

onboarding.adoc

This PR suggests adding some new material from [recently published work](https://www.redhat.com/en/blog/sharing-caring-building-clearer-contribution-paths-your-community) by @bproffitt.

Update with new material on basics

---

CONTRIBUTORS.md

@quaid I don't think I made a meaningful contribution to this chapter (although I was involved in some discussions with @palante on how to organize content in onboarding vs. mentoring chapters). Please feel free to remove me from the credits 😄

Removing myself from the mentoring chapter

---

build-book.sh

This adds epub to the output of the build process, using the asciidoctor-epub3 tool.

Adds epub to the build process.

---

incentivizing_rewarding_participants.adoc

This proposed chapter begins addresses #214 by offering an overview of various open source community reward models.

Reward models
